name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: cd Files && pip install -r requirements.txt

    - name: Run Python script and save output to file
      run: cd Files && python app.py

    - name: Run Splitter script and save output to file
      run: cd Files && python sort.py

    - name: Generate README
      run: cd Files && python generate_readme.py

    - name: Commit and push files
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "tahmaseb73"
        author_github: "https://github.com/tahmaseb73"
        message: "tahmaseb73_ConfigScavenger"
        add: "."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
